name: Publish docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v21

    - name: Build and load docker image
      run: "$(nix-build ./simple-httpfs-docker.nix) | docker load"

    - name: TODO
      run: "echo todo - publish / tag images to ECR"
