name: Build python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Debug CPU capabilities on worker
      run: lscpu

    - name: Install Nix
      uses: cachix/install-nix-action@v21

    - name: Build python package
      run: nix-build simple-httpfs.nix
